[build]
  command = ""
  publish = "deploy"

[context.deploy-preview]
  command = "npm run build-preview"

[context.production.environment]
  HUGO_VERSION = "0.29"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.29"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.29"

[context.branch-deploy]
  command = ""
  publish = "deploy"
